# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
    # for more opts see https://docs.vagrantup.com.
    
    # global ssh config
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    ## vagrant-vbguest plugin global config
    config.vbguest.auto_update = false
    # config.vbguest.no_remote = true

    # syntax: host_path, guest_path, [options]
    config.vm.synced_folder ENV['HOME'], ENV['HOME']

    config.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true

        # cpu count per vm
        vb.cpus = 2

        # Customize the amount of memory on the VM:
        vb.memory = "4096"

        vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vb.customize ["modifyvm", :id, "--vram", "256"]
    end

    config.vm.define "xenial" do |xenial|
        xenial.vm.box = "ubuntu/xenial64"
        xenial.vm.box_check_update = false
        xenial.vm.network "forwarded_port", guest: 22, host: 10022, host_ip: "127.0.0.1"

        xenial.vm.provision "shell", inline: <<-SHELL
            apt-get update

            apt-get install -y -q vim slurm
        SHELL
    end
    
    config.vm.define "linuxbrew" do |linuxbrew|
        if VAGRANT_COMMAND == "ssh"
            # run all setup as default box user, but ssh using custom user
            config.ssh.username = 'linuxbrew'
        end

        linuxbrew.vm.box = "ubuntu/trusty64"
        linuxbrew.vm.box_check_update = false
        linuxbrew.vm.network "forwarded_port", guest: 22, host: 10023, host_ip: "127.0.0.1"

        linuxbrew.vm.provision "shell", inline: <<-SHELL
            /vagrant/provision/linuxbrew_trusty_pkg_provision.sh
            /vagrant/provision/linuxbrew_brew_provision.sh vagrant
            
            /vagrant/provision/password_provision.sh root ubuntu vagrant linuxbrew
        SHELL
    end
    
    config.vm.define "linuxbrew_xenial", primary: true do |linuxbrew_xenial|
        if VAGRANT_COMMAND == "ssh"
            config.ssh.username = 'linuxbrew'
            #config.ssh.username = 'root'
            #config.ssh.password = 'vagrant'
            #config.ssh.insert_key = 'true'
        end

        linuxbrew_xenial.vm.box = "ubuntu/xenial64"
        linuxbrew_xenial.vm.box_check_update = false
        linuxbrew_xenial.vm.network "forwarded_port", guest: 22, host: 10024, host_ip: "127.0.0.1"

        linuxbrew_xenial.vm.provision "shell", inline: <<-SHELL
            /vagrant/provision/linuxbrew_xenial_pkg_provision.sh
            /vagrant/provision/linuxbrew_brew_provision.sh ubuntu

            /vagrant/provision/password_provision.sh root ubuntu linuxbrew
        SHELL
    end
end
